package contabilidad.bar;

import java.io.File;
import javax.swing.JOptionPane;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;

/**
 *
 * @author Kevin
 */
public class EditarProducto extends javax.swing.JFrame {

    public int cantidadProd=0;
    String archivo;
    String hoja = "INVENTARIO";
    public EditarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtPrecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CboxProductos = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        LbCodigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("EDITAR PRODUCTO");

        jLabel3.setText("DESCRIPCION:");

        jLabel4.setText("PRECIO DE VENTA:");

        jButton1.setText("ACTUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("PRODUCTO:");

        CboxProductos.setToolTipText("");
        CboxProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CboxProductosMouseClicked(evt);
            }
        });
        CboxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxProductosActionPerformed(evt);
            }
        });

        jLabel2.setText("CODIGO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDescripcion)
                            .addComponent(CboxProductos, 0, 147, Short.MAX_VALUE)
                            .addComponent(LbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CboxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LbCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CboxProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CboxProductosMouseClicked
    }//GEN-LAST:event_CboxProductosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String precio = this.TxtPrecio.getText();
        String descrip = this.TxtDescripcion.getText();
        precio=precio.replace(",", ".");
        int valido = validar(precio,descrip);
        int fila = Integer.valueOf(this.LbCodigo.getText());
        fila+=1;
        if (valido == 1){
            EscribirStrExcel(this.archivo, this.hoja,fila,1,this.TxtDescripcion.getText());
            EscribirStrExcel(this.archivo, this.hoja,fila,2,precio);
            JOptionPane.showMessageDialog(null,"Producto actualizado existosamente", "PRODUCTO EDITADO", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CboxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxProductosActionPerformed
        String celda, cod, des, pre;
        Cell cell;
        int fila = this.CboxProductos.getSelectedIndex();
        fila+=2;
        try{
            Workbook workbook = Workbook.getWorkbook(new File(this.archivo));
            Sheet sheet = workbook.getSheet(this.hoja);
            cell = sheet.getCell(0,fila);
            cod = cell.getContents();
            cell = sheet.getCell(1,fila);
            des = cell.getContents();
            cell = sheet.getCell(2,fila);
            pre = cell.getContents();
            workbook.close();
            this.LbCodigo.setText(cod);
            this.TxtDescripcion.setText(des);
            this.TxtPrecio.setText(pre);
        }        
        catch(Exception e){
            System.out.println("readExcel ->"+e);
        }
    }//GEN-LAST:event_CboxProductosActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CboxProductos;
    private javax.swing.JLabel LbCodigo;
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
   
    //FUNCION ESCRIBIR EXCEL   
    public void EscribirStrExcel(String archivo, String hoja, int fila, int columna, String valor){
        try{
            Workbook target_workbook = Workbook.getWorkbook(new File(archivo));
            WritableWorkbook workbook = Workbook.createWorkbook(new File(archivo), target_workbook);
            target_workbook.close();
            WritableSheet sheet = workbook.getSheet(hoja);
            jxl.write.Label label = new jxl.write.Label(columna, fila, valor);
            sheet.addCell(label);
            workbook.write();
            workbook.close();
        }

        catch(Exception e){
            System.out.println("writeExcel ->"+e);
        }
    }

    //FUNCION VALIDACION PRECIO
    public int validar(String prec, String descrip){
        try{
            double prueb = Double.valueOf(prec);
            if(descrip.equals("")){
                JOptionPane.showMessageDialog(null,"Porfavor llenar campo de descripcion", "ERROR DE DESCRIPCION", JOptionPane.ERROR_MESSAGE);
                return 0;
            }
            else{
                return 1;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Porfavor ingresar precio y stock numericos", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
    }
    
    //FUNCION REFRESCAR COMBOBOX PRODUCTOS
    public void CargarProductos(){
        String hoja = "INVENTARIO";
        String des;
        String celda;
        Cell cell;
        try{
            Workbook workbook = Workbook.getWorkbook(new File(archivo));
            Sheet sheet = workbook.getSheet(hoja);
            for (int k = 2; k <= this.cantidadProd+2; k++) {
                cell = sheet.getCell(1,k);
                des = cell.getContents();
                this.CboxProductos.addItem(des);
            }
            workbook.close();
        }
        catch(Exception e){
            System.out.println("readExcel ->"+e);
        }
    }
    

}
